from aisquared.base import DEFAULT_CONTAINER_RENDERING_CSS, DEFAULT_HTML_TAG_RENDERING_CSS, DEFAULT_TABLE_RENDERING_CSS, CONTAINER_RENDERING_CSS_FILE, HTML_TAG_RENDERING_CSS_FILE, TABLE_RENDERING_CSS_FILE
import json


def save_default_css():
    with open(CONTAINER_RENDERING_CSS_FILE, 'w') as f:
        json.dump(DEFAULT_CONTAINER_RENDERING_CSS, f)

    with open(HTML_TAG_RENDERING_CSS_FILE, 'w') as f:
        json.dump(DEFAULT_HTML_TAG_RENDERING_CSS, f)

    with open(TABLE_RENDERING_CSS_FILE, 'w') as f:
        json.dump(DEFAULT_TABLE_RENDERING_CSS, f)
